platform :ios, '7.0'

pod 'RESideMenu'
pod 'YTKNetwork'
pod 'SDWebImage'
pod 'UIActivityIndicator-for-SDWebImage'
pod 'Masonry'
pod 'AVOSCloud'
pod 'AVOSCloudIM'
pod 'AVOSCloudCrashReporting'
pod 'GRMustache', '~> 7.3.2'
pod 'BlocksKit'
